[workspace]
members = [
	"draft-core",
	"draft-server",
	"draft-state-machine",
	"draft-client",
	"draft-mini-redis",
]

[profile.release]
lto = "fat"
debug = true


[profile.dev.package.backtrace]
opt-level = 3
