name: Run tests and generate code coverage.
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      RUSTFLAGS: "-C opt-level=0"
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.20.0'
          args: '-o xml --output-dir target/tarpaulin --all-features'
      - name: Upload to codecov.
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x ./codecov
          ./codecov --token ${{ secrets.CODECOV_TOKEN }} --dir target/tarpaulin --verbose
      - name: Archive coverage results.
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: target/tarpaulin

