name: Run tests and generate code coverage.
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-o xml --output-dir target/tarpaulin --all-features --rustflags="-C opt-level=0"'
      - uses: codecov/codecov-action@v3
        with:
          token: $ {{ secrets.CODECOV_TOKEN }}
          files: target/tarpaulin/cobertura.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
      - name: Archive coverage results.
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: target/tarpaulin/cobertura.xml

